import type { GetTripsResponse, Trip } from "../model/trips.model";

const trips: Trip[] = [
  {
    id: 1,
    imageUrl: "/images/default-card.png",
    title: "Trip A",
    startDate: "2025.11.24",
    region: "서울",
    chatRoomId: 101,
  },
  {
    id: 2,
    imageUrl: "/images/default-card.png",
    title: "Trip B",
    startDate: "2025.12.02",
    region: "부산",
    chatRoomId: 102,
  },
  {
    id: 3,
    imageUrl: "/images/default-card.png",
    title: "Trip C",
    startDate: "2026.01.05",
    region: "제주",
    chatRoomId: 103,
  },
  {
    id: 4,
    imageUrl: "/images/default-card.png",
    title: "Trip D",
    startDate: "2026.02.18",
    region: "서울",
    chatRoomId: 104,
  },
  {
    id: 5,
    imageUrl: "/images/default-card.png",
    title: "Trip E",
    startDate: "2026.03.10",
    region: "강릉",
    chatRoomId: 105,
  },
  {
    id: 6,
    imageUrl: "/images/default-card.png",
    title: "Trip F",
    startDate: "2026.04.02",
    region: "여수",
    chatRoomId: 106,
  },
  {
    id: 7,
    imageUrl: "/images/default-card.png",
    title: "Trip G",
    startDate: "2026.04.20",
    region: "전주",
    chatRoomId: 107,
  },
  {
    id: 8,
    imageUrl: "/images/default-card.png",
    title: "Trip H",
    startDate: "2026.05.15",
    region: "속초",
    chatRoomId: 108,
  },
  {
    id: 9,
    imageUrl: "/images/default-card.png",
    title: "Trip I",
    startDate: "2026.06.05",
    region: "가평",
    chatRoomId: 109,
  },
  {
    id: 10,
    imageUrl: "/images/default-card.png",
    title: "Trip J",
    startDate: "2026.07.01",
    region: "경주",
    chatRoomId: 110,
  },
  {
    id: 11,
    imageUrl: "/images/default-card.png",
    title: "Trip K",
    startDate: "2026.07.22",
    region: "인천",
    chatRoomId: 111,
  },
  {
    id: 12,
    imageUrl: "/images/default-card.png",
    title: "Trip L",
    startDate: "2026.08.10",
    region: "춘천",
    chatRoomId: 112,
  },
  {
    id: 13,
    imageUrl: "/images/default-card.png",
    title: "Trip M",
    startDate: "2026.09.01",
    region: "대전",
    chatRoomId: 113,
  },
  {
    id: 14,
    imageUrl: "/images/default-card.png",
    title: "Trip N",
    startDate: "2026.09.25",
    region: "울산",
    chatRoomId: 114,
  },
  {
    id: 15,
    imageUrl: "/images/default-card.png",
    title: "Trip O",
    startDate: "2026.10.12",
    region: "광주",
    chatRoomId: 115,
  },
  {
    id: 16,
    imageUrl: "/images/default-card.png",
    title: "Trip P",
    startDate: "2026.11.05",
    region: "안동",
    chatRoomId: 116,
  },
  {
    id: 17,
    imageUrl: "/images/default-card.png",
    title: "Trip Q",
    startDate: "2026.12.03",
    region: "속초",
    chatRoomId: 117,
  },
  {
    id: 18,
    imageUrl: "/images/default-card.png",
    title: "Trip R",
    startDate: "2027.01.20",
    region: "부여",
    chatRoomId: 118,
  },
  {
    id: 19,
    imageUrl: "/images/default-card.png",
    title: "Trip S",
    startDate: "2027.02.14",
    region: "포항",
    chatRoomId: 119,
  },
  {
    id: 20,
    imageUrl: "/images/default-card.png",
    title: "Trip T",
    startDate: "2027.03.08",
    region: "제천",
    chatRoomId: 120,
  },
];

export const tripsMockResponse: GetTripsResponse = {
  success: true,
  status: 200,
  data: { content: trips, nextCursor: 13, hasNext: true, size: 3 },
};
